"""Added models

Revision ID: 680eaed17304
Revises:
Create Date: 2022-03-27 22:13:07.052613

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "680eaed17304"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("login", sa.String(length=256), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("first_name", sa.String(length=256), nullable=False),
        sa.Column("last_name", sa.String(length=256), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("sex", sa.Enum("MALE", "FEMALE", name="sex"), nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_dt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users_interests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("interest", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users_relations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("first_user_id", sa.BigInteger(), nullable=False),
        sa.Column("second_user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("REQUEST", "APPROVED", "REJECTED", name="relationstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_dt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["first_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["second_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_relations")
    op.drop_table("users_interests")
    op.drop_table("users")
    op.drop_table("cities")
    # ### end Alembic commands ###
