"""add unique login

Revision ID: ab0447753dcc
Revises: 680eaed17304
Create Date: 2022-03-28 00:48:29.368966

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab0447753dcc"
down_revision = "680eaed17304"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users", ["login"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    # ### end Alembic commands ###
